#!/bin/bash
#################################################
#	Title:	mk-lfs-x			#
#        Date:	2015-06-01			#
#     Version:	1.0				#
#      Author:	nielsterp@comhem.se		#
#     Options:	This script is designed to run	#
#		in CHROOT on your host system.	#
#		Do NOT attempt to run it from	#
#		your LFS environment !		#
#						#
#		Run as root or use sudo.	#
#################################################
#
#
set -o errexit				# exit if error...insurance ;)
set -o nounset				# exit if variable not initalized
set +h					# disable hashall
source config.inc
source function.inc
PRGNAME=${0##*/}			# script name minus the path
[ ${EUID} -eq 0 ] 	|| die "${PRGNAME}: Need to be root user: FAILURE"
[ -z ${PARENT} ]	&& die "${PRGNAME}: PARENT not set: FAILURE"
[ -z ${LFS} ]		&& die "${PRGNAME}: LFS not set: FAILURE"
	#
	#	Build X-Org, X libraries, Multimedia libraries and KDE
	#
	[ -d "${LFS}" ] && die "${PRGNAME}: Not in chroot environment: FAILURE"
	#
	# Packages for KDE
	LIST+="firefox "
	LIST+="VirtualBox "
	
	for i in ${LIST}; do
	  RPMPKG=""
	  rm -rf BUILD/* BUILDROOT/* > /dev/null 2>&1
	  RPMPKG=$(find RPMS -name "${i}-[0-9]*.rpm" -print)
	  [ -z $RPMPKG ] || printf "%s\n" "       Skipping: ${i}"
	  [ -z $RPMPKG ] && > "LOGS/${i}.log"	# clean log files
	  [ -z $RPMPKG ] && build "Building: ${i}" 'rpmbuild -ba --nocheck SPECS/${i}.spec' "LOGS/${i}.log"
	  [ -e LOGS/${i}.completed ] && continue;
	  RPMPKG=$(find RPMS -name "${i}-[0-9]*.rpm" -print)
	  [ -z $RPMPKG ] && die "installation error: rpm package not found\n"
	  build "Installing: ${i}" "rpm -ivh --nodeps --force ${RPMPKG}" "LOGS/${i}.completed" 
	done

msg "System finished !"
exit 0